### ISSUE TITLE
[BUG] JNI exceptions in console when having a lot of rebuilds or controller calls at once

### ISSUE THREAD

**Issue by josxha** [josxha/flutter-maplibre#136]
### Platforms

Android

### Version of flutter-maplibre

0.1.2

### Bug Description

When rebuilding the MapLibreMap widget a lot in a short amount of times the console shows JNI related exceptions.

```console
E/flutter (26853): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Use after release error
E/flutter (26853): #0      JReference.pointer (package:jni/src/jreference.dart:56:21)
E/flutter (26853): #1      MapLibreMap.moveCamera (package:maplibre/src/native/jni/org/maplibre/android/maps/MapLibreMap.dart:5280:27)
E/flutter (26853): #2      MapLibreMapStateJni.moveCamera.<anonymous closure> (package:maplibre/src/native/widget_state_jni.dart:221:14)
E/flutter (26853): #3      _platformIsolateMain.<anonymous closure> (dart:ui/platform_isolate.dart:142:51)
E/flutter (26853): #4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (26853): 
```

When hot restarting the app, another exception gets logged in the console:
```console
E/flutter (26880): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformIsolate shutdown unexpectedly
```

### Steps to Reproduce

Using the `MapLibreLayer` in flutter_map_maplibre, see bug report here: https://github.com/josxha/flutter_map_plugins/issues/54

### Expected Results

Don't throw any exceptions

### Actual Results

Exceptions in the console and future calls are partly unresponsive.

### Code Sample

```dart
// Paste your code here
```

**Comment by josxha** [comment]
This bug might solve itself when the platform and ui thread are merged. This is done on the `master` branch but not in the beta channel last time I checked. https://github.com/flutter/flutter/issues/150525

**Comment by bing127** [comment]
> This bug might solve itself when the platform and ui thread are merged. This is done on the `master` branch but not in the beta channel last time I checked. [flutter/flutter#150525](https://github.com/flutter/flutter/issues/150525)

Hello, may I ask if this will solve the problem of an input box at the bottom of a chat page that always moves up one frame slower than the keyboard?

**Comment by josxha** [comment]
> Hello, may I ask if this will solve the problem of an input box at the bottom of a chat page that always moves up one frame slower than the keyboard?

I'm not 100% certain but my guess is that is probably has no effect on that.

**Comment by josxha** [comment]
> It looks like there's a 1 frame delay when the insets change (eg during the keyboard opening animation). If this delay is caused by the insets being sent between platform code and Dart asynchronously

Looking up up flutter issue, it actually suggests that it will have an effect.

> When can I try it out on my end?

You can try it out once it's ready. Please stop abusing other repositories for discussions.
