### ISSUE TITLE
[FEATURE] Support for Android 5.x

### ISSUE THREAD

**Issue by josxha** [josxha/flutter-maplibre#25]
### Feature Description

It is possible to support android devices with android 5.0 and 5.1 (sdk version 21, 22) by using an virtual display.
According to [Statista](https://www.statista.com/statistics/921152/mobile-android-version-share-worldwide/) Android 5.x has still a 1% market share.

### Describe alternatives you've considered

Alternative: don't add support for those SDK versions.

### Additional context

- https://github.com/flutter/flutter/blob/master/docs/platforms/android/Virtual-Display.md

**Comment by josxha** [comment]
Integration tests for Android 5.x don't succeed
```console
00:00 +0: loading /home/runner/work/flutter-maplibre/flutter-maplibre/example/integration_test/controller_test.dart
Running Gradle task 'assembleDebug'...                          
Warning: Errors during XML parse:
Warning: Additionally, the fallback loader failed to parse the XML.
Checking the license for package NDK (Side by side) 26.1.10909125 in /usr/local/lib/android/sdk/licenses
License for package NDK (Side by side) 26.1.10909125 accepted.
Preparing "Install NDK (Side by side) 26.1.10909125 v.26.1.10909125".
"Install NDK (Side by side) 26.1.10909125 v.26.1.10909125" ready.
Installing NDK (Side by side) 26.1.10909125 in /usr/local/lib/android/sdk/ndk/26.1.10909125
"Install NDK (Side by side) 26.1.10909125 v.26.1.10909125" complete.
"Install NDK (Side by side) 26.1.10909125 v.26.1.10909125" finished.
Running Gradle task 'assembleDebug'...                             97.9s
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Installing build/app/outputs/flutter-apk/app-debug.apk...           7.0s
00:00 +0: controller render map
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following PlatformException was thrown running a test:
PlatformException(error, Platform views cannot be displayed below API level 23You can prevent this
issue by setting `minSdkVersion: 23` in build.gradle., null,
java.lang.UnsupportedOperationException: Platform views cannot be displayed below API level 23You
can prevent this issue by setting `minSdkVersion: 23` in build.gradle.
	at
io.flutter.plugin.platform.SurfaceTexturePlatformViewRenderTarget.<init>(SurfaceTexturePlatformViewRenderTarget.java:62)
	at
io.flutter.plugin.platform.PlatformViewsController.makePlatformViewRenderTarget(PlatformViewsController.java:1000)
	at
io.flutter.plugin.platform.PlatformViewsController.configureForVirtualDisplay(PlatformViewsController.java:557)
	at io.flutter.plugin.platform.PlatformViewsController.access$800(PlatformViewsController.java:51)
	at
io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:226)
	at
io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
	at
io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
	at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
	at
io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at
io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:[135](https://github.com/josxha/flutter-maplibre/actions/runs/11652026281/job/32442719681#step:7:139))
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
)

When the exception was thrown, this was the stack:
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1164:28)
<asynchronous suspension>
#3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:827:5)
<asynchronous suspension>
#4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:854:7)
<asynchronous suspension>
#5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:176:29)
<asynchronous suspension>

The test description was:
  render map
════════════════════════════════════════════════════════════════════════════════════════════════════
00:01 +0 -1: controller render map [E]
  Test failed. See exception logs above.
  The test description was: render map
  
  'package:flutter_test/src/binding.dart': Failed assertion: line 2059 pos 12: '_pendingFrame == null': is not true.
  dart:core                                                                  _AssertionError._throwNew
  package:flutter_test/src/binding.dart 2059:12                              LiveTestWidgetsFlutterBinding.postTest
  ===== asynchronous gap ===========================
  package:stream_channel                                                     _GuaranteeSink.add
  tmp/flutter_tools.PYSNSP/flutter_test_listener.XYATWF/listener.dart 53:22  main.<fn>
  
00:01 +0 -1: controller getCamera
00:01 +0 -2: controller getCamera [E]
  'package:flutter_test/src/binding.dart': Failed assertion: line 2034 pos 12: '!inTest': is not true.
  dart:core                                                                  _AssertionError._throwNew
  package:flutter_test/src/binding.dart 2034:12                              LiveTestWidgetsFlutterBinding.runTest
  package:integration_test/integration_test.dart 234:17                      IntegrationTestWidgetsFlutterBinding.runTest
  package:flutter_test/src/widget_tester.dart 181:24                         testWidgets.<fn>
  ===== asynchronous gap ===========================
  package:stream_channel                                                     _GuaranteeSink.add
  tmp/flutter_tools.PYSNSP/flutter_test_listener.XYATWF/listener.dart 53:22  main.<fn>
  
  'package:flutter_test/src/binding.dart': Failed assertion: line 2058 pos 12: '!_expectingFrame': is not true.
  dart:core                                                                  _AssertionError._throwNew
  package:flutter_test/src/binding.dart 2058:12                              LiveTestWidgetsFlutterBinding.postTest
  ===== asynchronous gap ===========================
  package:stream_channel                                                     _GuaranteeSink.add
  tmp/flutter_tools.PYSNSP/flutter_test_listener.XYATWF/listener.dart 53:22  main.<fn>
  
00:01 +0 -2: controller moveCamera
00:01 +0 -2: controller render map
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test (but after the test had completed):
A SemanticsHandle was active at the end of the test.
All SemanticsHandle instances must be disposed by calling dispose() on the SemanticsHandle.

When the exception was thrown, this was the stack:
#0      WidgetTester._verifySemanticsHandlesWereDisposed (package:flutter_test/src/widget_tester.dart:1075:7)
#1      WidgetTester._endOfTestVerifications (package:flutter_test/src/widget_tester.dart:1066:5)
#2      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1044:22)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
00:01 +0 -2: controller render map [E]
  Test failed. See exception logs above.
  The test description was: render map
  
00:01 +0 -3: controller moveCamera [E]
  'package:flutter_test/src/binding.dart': Failed assertion: line 2034 pos 12: '!inTest': is not true.
  dart:core                                                                  _AssertionError._throwNew
  package:flutter_test/src/binding.dart 2034:12                              LiveTestWidgetsFlutterBinding.runTest
  package:integration_test/integration_test.dart 234:17                      IntegrationTestWidgetsFlutterBinding.runTest
  package:flutter_test/src/widget_tester.dart [181](https://github.com/josxha/flutter-maplibre/actions/runs/11652026281/job/32442719681#step:7:185):24                         testWidgets.<fn>
  ===== asynchronous gap ===========================
  package:stream_channel                                                     _GuaranteeSink.add
  tmp/flutter_tools.PYSNSP/flutter_test_listener.XYATWF/listener.dart 53:22  main.<fn>
  
00:01 +0 -3: (tearDownAll)
Package uninstall error: Failure [DELETE_FAILED_INTERNAL_ERROR]
00:02 +0 -3: Some tests failed.
Error: The process '/usr/bin/sh' failed with exit code 1
Terminate Emulator
INFO    | Snapshots have been disabled by the user, save request is ignored.
ERROR   | stop: Not implemented
WARNING | Emulator client has not yet been configured.. Call configure me first!
```

**Comment by josxha** [comment]
It is currently unclear if Android SDK version 21 and 22 can be supported at all: https://docs.flutter.dev/release/breaking-changes/3-19-deprecations#android-platform-views-on-api-22-and-below

> As of Flutter 3.0 platform views require api 23 or higher. In Flutter 3.19 we now throw UnsupportedOperationException when using platform views on android devices running api level 22 and below.

Closing this issue off for now as not planned. If someone finds a way to add support, we can reopen this issue.
